#!/bin/bash
set -e

bundle_test_unit() {
	date

#	pkg_list=$(go list -e \
#		-f '{{if ne .Name "github.com/docker/docker"}}
#			{{.ImportPath}}
#		    {{end}}' \
#		./...)

	go test github.com/docker/docker/api
}

bundle_test_unit 2>&1 | tee -a "$DEST/test.log"
